### PR TITLE
New Year's PR: iPad icons and support

### PR DESCRIPTION
**Pull request by LeonardoCardoso**
## Changes in this pull request

- Fresh icons
- iPad Support

Issue fixeds: #62 #84

### Checklist

- [x] Project builds and runs as expected.
- [x] No new linting violations have been introduced.
- [x] I have reviewed the [contributing guide](https://github.com/unnamedd/swift-evolution/blob/development/.github/CONTRIBUTING.md)
- [x] I'm attaching to this PR some screenshots (if applicable)

## Icons

screen shot 2017-12-29 at 18 53 22
screen shot 2017-12-29 at 18 53 26

### Portrait

simulator screen shot - ipad pro 9 7-inch - 2017-12-29 at 16 43 39
simulator screen shot - ipad pro 9 7-inch - 2017-12-29 at 16 43 47
simulator screen shot - ipad pro 9 7-inch - 2017-12-29 at 16 43 51

### Landscape

simulator screen shot - ipad pro 9 7-inch - 2017-12-29 at 16 43 59
simulator screen shot - ipad pro 9 7-inch - 2017-12-29 at 16 44 01

### Form Sheets

simulator screen shot - ipad pro 9 7-inch - 2017-12-29 at 16 44 09
simulator screen shot - ipad pro 9 7-inch - 2017-12-29 at 17 05 16

### CODE REVIEW

**Comment by unnamedd** [comment]
@LeonardoCardoso, after some tests, let me give you some feedback:
- [ ] Share proposal isn't working
- [ ] After changing the display mode of proposal detail to full screen, there is no chance to come back, only tapping on _"Evolution"_. Will be nice to have this option instead 'kill' this button.
- [ ] If there is no proposal selected, will be nice to not show the _full screen_ and _share_ buttons.

**Comment by LeonardoCardoso** [comment]
@unnamed I’ll take a look!

**Comment by leonardocardoso** [comment]
@unnamedd I’ll take a look!

**Comment by LeonardoCardoso** [comment]
@unnamedd I’ll take a look!

**Comment by leonardocardoso** [comment]
@unnamedd The "full screen button" is part of the `UISplitViewController` fragment, and that is the default behavior: Full Screen -> Back Button. It's actually hiding the master controller, not really going full screen. I didn't find a way to hide that button at will without keeping showing Master and Details at the same time.

There are three different modes on `UISplitViewController`:

- `primaryHidden`: Hide the master controller when the split controller is shown, without the "full screen button";
- `primaryOverlay`: Show the master controller over the details when the split controller is shown, without the "full screen button";
- `allVisible`: Show both at the same time with the "full screen button" when the split controller is shown.

## Share Button

It's being displayed only when the proposal is loaded.

## Share Action

simulator screen shot - ipad pro 9 7-inch - 2017-12-30 at 14 16 27
simulator screen shot - ipad pro 9 7-inch - 2017-12-30 at 14 16 22

**Pull request merged**
